"use client";

import React, { useState, useEffect } from "react";

type BlockType = 
  | { type: "header"; data: { text: string; level: number } }
  | { type: "paragraph"; data: { text: string } }
  | { type: "list"; data: { style: string; items: string[] } };

type ContentType = {
  time: number;
  blocks: BlockType[];
};

const DataDeletionPolicy = () => {
  const [content, setContent] = useState<ContentType>({
    time: new Date().getTime(),
    blocks: [
      {
        "type": "header",
        "data": {
          "text": "Data Deletion Policy for Swasthi",
          "level": 1
        }
      },
      {
        "type": "paragraph",
        "data": {
          "text": "Last Updated: 09.11.2024"
        }
      },
      {
        "type": "paragraph",
        "data": {
          "text": "At Swasthi, we are committed to ensuring that our users have control over their personal data. This Data Deletion Policy outlines the processes and procedures for the deletion of your personal information collected and stored by the Swasthi mobile application (\"App\"). By using our App, you agree to the terms described in this policy. If you do not agree with this policy, please do not use the App."
        }
      },
      {
        "type": "header",
        "data": {
          "text": "1. User Rights to Data Deletion",
          "level": 2
        }
      },
      {
        "type": "paragraph",
        "data": {
          "text": "1.1 Right to Erasure: Users have the right to request the deletion of their personal data that has been collected and stored by the App. This right is in line with data protection regulations, including the General Data Protection Regulation (GDPR) and other applicable data collection laws of India."
        }
      },
      {
        "type": "paragraph",
        "data": {
          "text": "1.2 Types of Data Eligible for Deletion: Personal Information: This includes any data you provided during registration or use of the App, such as your email address, username, height, weight, age, and gender. Usage Data: Information generated by your use of the App, including interaction data, logs, and preferences. Any other personal information processed by the App."
        }
      },
      {
        "type": "header",
        "data": {
          "text": "2. How to Request Data Deletion",
          "level": 2
        }
      },
      {
        "type": "paragraph",
        "data": {
          "text": "2.1 Submitting a Request: To request the deletion of your data, please contact us via email at help.swasthi@gmail.com or info@swasthi.fit with the subject line \"Data Deletion Request.\" Include the following information in your request: Your full name, registered email address associated with your Swasthi account, a description of the data you wish to delete, and a statement confirming that you are the owner of the account."
        }
      },
      {
        "type": "paragraph",
        "data": {
          "text": "2.2 Verification Process: Once a data deletion request is received, we will verify the identity of the requestor to ensure that the person making the request is the account holder or an authorized representative. Verification may include sending an email to the registered email address, requesting confirmation of account information, or requiring additional documentation to confirm your identity."
        }
      },
      {
        "type": "header",
        "data": {
          "text": "3. Timeframe for Data Deletion",
          "level": 2
        }
      },
      {
        "type": "paragraph",
        "data": {
          "text": "3.1 Processing Time: Upon successful verification of your identity, we will process your data deletion request within 7 calendar days. In certain situations, such as when the request is complex or involves a large volume of data, this period may be extended by an additional 4 - 6 weeks. We will inform you of any such extension and the reasons for the delay."
        }
      },
      {
        "type": "paragraph",
        "data": {
          "text": "3.2 Notification of Deletion: You will receive a confirmation email once your data has been deleted. This notification will provide details of the data deleted and the date of deletion."
        }
      },
      {
        "type": "header",
        "data": {
          "text": "4. Consequences of Data Deletion",
          "level": 2
        }
      },
      {
        "type": "paragraph",
        "data": {
          "text": "4.1 Account Termination: Deleting your personal data will result in the termination of your Swasthi account. You will no longer have access to the App, including any data, features, or subscriptions associated with your account."
        }
      },
      {
        "type": "paragraph",
        "data": {
          "text": "4.2 Loss of Data and Services: Once your data is deleted, it cannot be recovered. All health metrics, progress, preferences, and any other data associated with your account will be permanently erased."
        }
      },
      {
        "type": "paragraph",
        "data": {
          "text": "4.3 Impact on Subscriptions: If you have an active subscription, deleting your account will result in the immediate termination of your subscription. No refunds will be issued for any unused portion of the subscription period."
        }
      },
      {
        "type": "header",
        "data": {
          "text": "5. Exceptions to Data Deletion",
          "level": 2
        }
      },
      {
        "type": "paragraph",
        "data": {
          "text": "5.1 Retention for Legal Compliance: Certain data may be retained for a limited period to comply with legal obligations, resolve disputes, enforce our terms and conditions, or protect our legal rights. This may include retaining data required for accounting, auditing, and regulatory compliance purposes."
        }
      },
      {
        "type": "header",
        "data": {
          "text": "6. Changes to This Data Deletion Policy",
          "level": 2
        }
      },
      {
        "type": "paragraph",
        "data": {
          "text": "6.1 Policy Updates: We may update this Data Deletion Policy from time to time to reflect changes in our practices, legal requirements, or operational needs. We will notify you of any significant changes through in-app notifications or other means. Your continued use of the App after the effective date of the updated policy constitutes your acceptance of the changes."
        }
      },
      {
        "type": "header",
        "data": {
          "text": "7. Contact Information",
          "level": 2
        }
      },
      {
        "type": "paragraph",
        "data": {
          "text": "7.1 Contact Us: If you have any questions, concerns, or requests regarding this Data Deletion Policy or your personal information, please contact us at: Email: help.swasthi@gmail.com or info@swasthi.fit Address: 395, Purav Deen Dayal, Old Railway Road, Veer Bhawan Nagar, Roorkee-247667, India"
        }
      }
    ],
  });

  // Fetch existing content from backend
  useEffect(() => {
    const fetchContent = async () => {
      try {
        const response = await fetch(
          "https://admin-panel-backend-knoh.onrender.com/api/datadeletion"
        );
        if (!response.ok) throw new Error("Failed to fetch content");

        const data: { content: ContentType } = await response.json();
        setContent(data.content);
      } catch (error) {
        console.error("Error fetching content:", error);
      }
    };
    fetchContent();
  }, []);

  // Render blocks with validation for text content
  const renderText = (text: string | undefined) => {
    if (!text) return null;
    return <span dangerouslySetInnerHTML={{ __html: text }} />;
  };

  return (
    <div className="min-h-screen flex bg-black text-white pt-4 pb-4">
      <div className="max-w-7xl mx-auto bg-neutral-900 mt-11 p-11 rounded-lg shadow-lg border border-gray-700">
        <div className="bg-custom-gradient shadow-lg shadow-white p-4 rounded-lg border border-gray-600">
          {content.blocks.map((block, index) => {
            switch (block.type) {
              case "header":
                return (
                  <h2 key={index} className="text-lg font-bold text-white mb-2">
                    {block.data.text}
                  </h2>
                );
              case "paragraph":
                return (
                  <p key={index} className="text-gray-300 mb-2">
                    {renderText(block.data.text)}
                  </p>
                );
              case "list":
                return (
                  <ol
                    key={index}
                    className="list-decimal pl-6 text-gray-300 mb-2"
                  >
                    {block.data.items.map((item, i) => (
                      <li key={i}>{item}</li>
                    ))}
                  </ol>
                );
              default:
                return null;
            }
          })}
        </div>
      </div>
    </div>
  );
};

export default DataDeletionPolicy;
